#!/usr/bin/env node
/**
 * Ensure a minimal .env exists with the default local Postgres URL.
 * Safe to run repeatedly — never overwrites an existing .env.
 */
import { access, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL, fileURLToPath } from "node:url";
import { getDefaultDatabaseUrl, resolvePostgresBackend } from "./postgres-config.mjs";

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const ENV_PATH = path.join(ROOT, ".env");

function envTemplate(databaseUrl) {
  return `# Auto-generated by Next — local Postgres (managed automatically).
# Do not edit unless you use an advanced external-database setup.
DATABASE_URL="${databaseUrl}"
`;
}

async function fileExists(filePath) {
  try {
    await access(filePath);
    return true;
  } catch {
    return false;
  }
}

async function loadExistingEnv() {
  if (!(await fileExists(ENV_PATH))) return;
  const contents = await readFile(ENV_PATH, "utf8");
  for (const line of contents.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const match = trimmed.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);
    if (!match) continue;
    const key = match[1];
    let value = match[2]?.trim() ?? "";
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    if (!process.env[key]) {
      process.env[key] = value;
    }
  }
}

export async function ensureEnvFile() {
  if (!(await fileExists(ENV_PATH))) {
    const databaseUrl = getDefaultDatabaseUrl(resolvePostgresBackend());
    await writeFile(ENV_PATH, envTemplate(databaseUrl), { mode: 0o600 });
    console.log("Created .env with default DATABASE_URL for local Postgres.");
  }

  await loadExistingEnv();

  if (!process.env.DATABASE_URL?.trim()) {
    process.env.DATABASE_URL = getDefaultDatabaseUrl(resolvePostgresBackend());
  }
}

function isMainModule() {
  const entry = process.argv[1];
  if (!entry) return false;
  return import.meta.url === pathToFileURL(path.resolve(entry)).href;
}

if (isMainModule()) {
  ensureEnvFile().catch((error) => {
    console.error(error instanceof Error ? error.message : error);
    process.exit(1);
  });
}
